DUT_Port:
  dut_1: 2-1
  dut_2: 2-2
  dut_3: 2-3

hyperion:
  hyperion_1: 02376
  hyperion_2: 02377
  hyperion_3: 02378


boardIO:
  #input
  _ADDRESS_START_BUTTON_1_STATUS: 1
  _ADDRESS_DUT_POSITION_STATUS : 2
  _ADDRESS_TYPEC_IN_HOME_1_STATUS: 3
  _ADDRESS_TYPEC_IN_TEST_1_STATUS: 4
  _ADDRESS_DUT_CLAMPING_IN_HOME_1_STATUS: 5
  _ADDRESS_DUT_CLAMPING_IN_TEST_1_STATUS: 6
  _ADDRESS_START_BUTTON_2_STATUS: 7
  _ADDRESS_CHECK_DUT_2_STATUS: 8   #new
  _ADDRESS_TYPEC_IN_HOME_2_STATUS: 9
  _ADDRESS_TYPEC_IN_TEST_2_STATUS: 10
  _ADDRESS_DUT_CLAMPING_IN_HOME_2_STATUS: 11
  _ADDRESS_DUT_CLAMPING_IN_TEST_2_STATUS: 12
  _ADDRESS_START_BUTTON_3_STATUS: 13
  _ADDRESS_CHECK_DUT_3_STATUS: 14
  _ADDRESS_TYPEC_IN_HOME_3_STATUS: 15
  _ADDRESS_TYPEC_IN_TEST_3_STATUS: 16
  _ADDRESS_DUT_CLAMPING_IN_HOME_3_STATUS: 17
  _ADDRESS_DUT_CLAMPING_IN_TEST_3_STATUS: 18
  _ADDRESS_CHECK_DUT_1_STATUS: 2

  #output 1
  _ADDRESS_START_LIGHT_1_CONTROL: 1
  _ADDRESS_TYPEC_1_CONTROL: 2
  _ADDRESS_CLAMPING_TEST_1_CONTROL: 3
  _ADDRESS_RED_LIGHT_1_CONTROL: 4
  _ADDRESS_GREEN_LIGHT_1_CONTROL: 5
  _ADDRESS_START_LIGHT_2_CONTROL: 6
  _ADDRESS_TYPEC_2_CONTROL: 7
  _ADDRESS_CLAMPING_TEST_2_CONTROL: 8
  _ADDRESS_RED_LIGHT_2_CONTROL: 9
  _ADDRESS_GREEN_LIGHT_2_CONTROL: 10
  _ADDRESS_START_LIGHT_3_CONTROL: 11
  _ADDRESS_TYPEC_3_CONTROL: 12
  _ADDRESS_CLAMPING_TEST_3_CONTROL: 13
  _ADDRESS_RED_LIGHT_3_CONTROL: 14
  _ADDRESS_GREEN_LIGHT_3_CONTROL: 15
  #output 2
  _ADDRESS_CLAMPING_HOME_1_CONTROL: 1
  _ADDRESS_CLAMPING_HOME_2_CONTROL: 2
  _ADDRESS_CLAMPING_HOME_3_CONTROL: 3




