motor:
  motor_disable: False
  center_position: 70
  down_position: 30
  speed: 100
  acceleration: 200
  ratio: 1
  lead: 10

boardIO_OA:
  #input
  _ADDRESS_START_BUTTON_STATUS: 1
  _ADDRESS_DOOR_STATUS: 2

  _ADDRESS_TYPEC_HOME_STATUS: 4
  _ADDRESS_TYPEC_TEST_STATUS: 5
  _ADDRESS_CLAMPING_HOME_STATUS: 6
  _ADDRESS_CLAMPING_TEST_STATUS: 7
  _ADDRESS_SPIN_HOME_STATUS: 8
  _ADDRESS_SPIN_TEST_STATUS: 9

  #output
  _ADDRESS_RED_LIGHT_1_CONTROL: 4
  _ADDRESS_GREEN_LIGHT_1_CONTROL: 5
  _ADDRESS_TYPEC_CONTROL: 7
  _ADDRESS_CLAMPING_CONTROL: 8
  _ADDRESS_SPIN_HOME_CONTROL: 9
  _ADDRESS_SPIN_TEST_CONTROL: 10









