boardIO:
  #input
  _ADDRESS_EMERGENCY_STOP_STATUS: 1
  _ADDRESS_START_BUTTON_STATUS: 3
  _ADDRESS_STOP_BUTTON_STATUS: 4
  _ADDRESS_RESET_BUTTON_STATUS: 5
  _ADDRESS_CLAMPING_HOME_STATUS: 11
  _ADDRESS_CLAMPING_TEST_STATUS: 12
  _ADDRESS_DUT_POSITION_STATUS: 10
  _ADDRESS_TYPEC_HOME_STATUS: 2
  _ADDRESS_TYPEC_TEST_STATUS: 9

  #output
  _ADDRESS_TYPEC_CONTROL: 1
  _ADDRESS_START_BUTTON_CONTROL: 2
  _ADDRESS_STOP_BUTTON_CONTROL: 3
  _ADDRESS_BLUE_LIGHT_CONTROL: 4
  _ADDRESS_RED_LIGHT_CONTROL: 5
  _ADDRESS_GREEN_LIGHT_CONTROL: 6
  _ADDRESS_BUZZING_CONTROL: 7
  _ADDRESS_RESET_BUTTON_CONTROL: 8
  _ADDRESS_CLAMPING_CONTROL: 9

light_config:
  light_disable: True
  channel: 0
  value: 100


