#IO Card 1
boardIO_1: 
  #input
  _ADDRESS_EMERGENCY_STOP_STATUS: 1
  _ADDRESS_START_BUTTON_STATUS: 2
  _ADDRESS_RESET_BUTTON_STATUS: 4
  _ADDRESS_SAFETY_CURTAIN_STATUS: 5
  _ADDRESS_GAS_CHECK_STATUS: 6
  _ADDRESS_DOOR_OPEN_STATUS: 9
  _ADDRESS_DOOR_CLOSE_STATUS: 10
  _ADDRESS_ROTATE_TEST_STATUS: 11
  _ADDRESS_ROTATE_ORIGIN_STATUS: 12

  #output
  _ADDRESS_START_BUTTON_CONTROL: 1
  _ADDRESS_RESET_BUTTON_CONTROL: 3
  _ADDRESS_RED_LIGHT_CONTROL: 12
  _ADDRESS_GREEN_LIGHT_CONTROL: 13
  _ADDRESS_DOOR_CLOSE_CONTROL: 8
  _ADDRESS_DOOR_OPEN_CONTROL: 9
  _ADDRESS_ROTATE_TEST_CONTROL: 10
  _ADDRESS_ROTATE_ORIGIN_CONTROL: 11
  
#IO Card 2
boardIO_2: 
  #input
  # DUT 1
  _ADDRESS_TYPEC1_TEST_STATUS: 2
  _ADDRESS_TYPEC1_ORIGIN_STATUS: 3
  _ADDRESS_DUT1_CHECK_STATUS: 6
  # DUT 2
  _ADDRESS_TYPEC2_TEST_STATUS: 4
  _ADDRESS_TYPEC2_ORIGIN_STATUS: 5
  _ADDRESS_DUT2_CHECK_STATUS: 7

  #output
  # DUT 1
  _ADDRESS_TYPEC1_INSERT_CONTROL: 1

  # DUT 2  
  _ADDRESS_TYPEC2_INSERT_CONTROL: 2

  



