boardIO:
  #input 1
  _ADDRESS_EMERGENCY_STOP_STATUS: 1
  _ADDRESS_START_BUTTON_STATUS: 2
  _ADDRESS_STOP_BUTTON_STATUS: 2
  _ADDRESS_RESET_BUTTON_STATUS: 4
  _ADDRESS_GRATING_STATUS: 5
  _ADDRESS_TYPEC_1_HOME_STATUS: 9
  _ADDRESS_TYPEC_1_TEST_STATUS: 10
  _ADDRESS_CLAMPING_1_HOME_STATUS: 11
  _ADDRESS_CLAMPING_1_TEST_STATUS: 12
  _ADDRESS_DUT_1_POSITION_STATUS: 13
  _ADDRESS_HOLDER_1_UPDOWN_TEST_STATUS: 14
  _ADDRESS_HOLDER_1_UPDOWN_HOME_STATUS: 15
  _ADDRESS_HOLDER_1_TRAN_HOME_STATUS: 17
  _ADDRESS_HOLDER_1_TRAN_TEST_STATUS: 18


  #input 2
  _ADDRESS_TYPEC_2_HOME_STATUS: 1
  _ADDRESS_TYPEC_2_TEST_STATUS: 2
  _ADDRESS_CLAMPING_2_HOME_STATUS: 3
  _ADDRESS_CLAMPING_2_TEST_STATUS: 4
  _ADDRESS_DUT_2_POSITION_STATUS: 5
  _ADDRESS_HOLDER_2_TRAN_HOME_STATUS: 9
  _ADDRESS_HOLDER_2_TRAN_TEST_STATUS: 10
  _ADDRESS_DOOR_HOME_STATUS: 13
  _ADDRESS_DOOR_TEST_STATUS: 14

  #output 1
  _ADDRESS_START_BUTTON_CONTROL: 1
  _ADDRESS_STOP_BUTTON_CONTROL: 2
  _ADDRESS_BLUE_LIGHT_CONTROL: 3
  _ADDRESS_RED_LIGHT_CONTROL: 4
  _ADDRESS_GREEN_LIGHT_CONTROL: 5
  _ADDRESS_BUZZING_CONTROL: 6
  _ADDRESS_RESET_BUTTON_CONTROL: 7
  _ADDRESS_TYPEC_1_CONTROL: 8
  _ADDRESS_CLAMPING_1_CONTROL: 9
  _ADDRESS_HOLDER_1_UPDOWN_HOME_CONTROL: 10
  _ADDRESS_HOLDER_1_UPDOWN_TEST_CONTROL: 11
  _ADDRESS_HOLDER_1_TRAN_HOME_CONTROL: 12
  _ADDRESS_HOLDER_1_TRAN_TEST_CONTROL: 13

  #output 2
  _ADDRESS_TYPEC_2_CONTROL: 1
  _ADDRESS_CLAMPING_2_CONTROL: 2
  _ADDRESS_HOLDER_2_TRAN_HOME_CONTROL: 3
  _ADDRESS_HOLDER_2_TRAN_TEST_CONTROL: 4
  _ADDRESS_DOOR_HOME_CONTROL: 5
  _ADDRESS_DOOR_TEST_CONTROL: 6

light_control:
  channel: 1
  value: 500

DUT_Port:
  DUT_1: 1-7.1.2
  DUT_2: 1-7.1.3






